### ISSUE TITLE
Add re-write rule for the 1.1.0 collections and portals schemas

### ISSUE THREAD

**Issue by robyngit** [DataONEorg/dataone_purl#4]

**Comment by gothub** [comment]
@robyngit these schemas aren't yet available on purl.dataone.org. Does @datadavev make the link?

**Comment by mbjones** [comment]
@gothub you should be able to prepare the changes needed. purl links need to go to stable, tagged locations. Links are managed through the git repo for the purl redirector (https://github.com/DataONEorg/dataone_purl), which would then need to be deployed by someone with sysadmin rights (nick, chris, jing, dave, me IIRC, but there could be others) as described in the README there.

**Comment by gothub** [comment]
OK, [PR](https://github.com/DataONEorg/dataone_purl/pull/5) submitted.

**Comment by gothub** [comment]
These URLs are now available:
- https://purl.dataone.org/portals-1.1.0 
- https://purl.dataone.org/collections-1.1.0

**Comment by robyngit** [comment]
Thanks @gothub !
